version: "3.7"

x-common-conf: &common-conf
  build: ./src
  restart: unless-stopped
  depends_on:
    - redis
  environment:
    RQ_REDIS_URL: "redis://redis"
    SCHEDULER_API_BASE: "http://web:8000"

services:
  web:
    <<: *common-conf
    ports:
      - 8000:8000

  worker: &worker
    <<: *common-conf
    entrypoint: ["rq", "worker"]

  worker2:
    <<: *worker

  worker3:
    <<: *worker

  redis:
    image: redis:alpine
    restart: unless-stopped

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 8f6c8ad690ffc5438ea1e899
