version: "3.7"

x-common-conf: &common-conf
  image: janwh/testscheduler
  build: ./
  restart: unless-stopped
  depends_on:
    - redis
  volumes:
    - ./tests:/app/tests:ro

services:
  web:
    <<: *common-conf
    ports:
      - 8000:8000
    environment:
      REDIS_URL: "redis://redis"
      DATABASE_URL: "postgres://postgres:SecurePassw0rd@db:5432/postgres"

  worker: &worker
    <<: *common-conf
    entrypoint: ["python", "-m", "testscheduler", "worker"]
    environment:
      REDIS_URL: "redis://redis"
      SCHEDULER_API_BASE: "http://web:8000"

  redis:
    image: redis:alpine
    restart: unless-stopped

  db:
    image: postgres:11-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: SecurePassw0rd
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
